### PR TITLE
2.0 sedml l1 v3

### PR DESCRIPTION
**Pull request by matthiaskoenig**
Merging my latest changes back into master
- updated the bioservices related model loading
- I am having a major issues with NaNs due to process_traces. This is fixing this.

### CODE REVIEW

**Comment by 0u812** [comment]
Hi Matthias, the nans in process_trace were added so that I could plot the repeated task examples from the SED-ML Web Tools without having lines joining successive traces (i.e. the trace for each repeated task should be disjoint). With these changes, I get:

selection_078

whereas in master I get:

selection_079

What if we only apply process trace to results which are plotted and not to reports? Would that work for you?

**Comment by matthiaskoenig** [comment]
Hi Kyle, 

with the nans at the end the datagenerators have the wrong length (and content). Which becomes problematic when I want to export data underlying plot2Ds. 
Also I get problems plotting the results in JavaScript plotly.js which can't handle nan values in plots.

There has to be a better solution than adding nans at the end. 
In which python module do you plot the lines, so I can have a look?

**Comment by 0u812** [comment]
Hi Matthias, those screenshots I posted above were made with Plotly 2.0.12. I'm using the[ timecourse scan example from SWT](http://sysbioapps.dyndns.org/SED-ML_Web_Tools/Home/SimulateUrl?url=http%3A%2F%2Fsvn.code.sf.net%2Fp%2Flibsedml%2Fcode%2Ftrunk%2FSamples%2Fsedx-archives%2Fnestedv3%2Fv3-example4-repeated-scan-oscli.sedx). I'm using the following inline OMEX, which you can run with `te.executeInlineOmex`.

```
%model model1.xml
// -- Begin Antimony block converted from model1.xml
// Created by libAntimony v2.9.3
model *oscli()

  // Compartments and Species:
  compartment compartment_;
  species S1 in compartment_, S2 in compartment_, $X0 in compartment_, $X1 in compartment_;
  species $X2 in compartment_;

  // Reactions:
  J0: $X0 => S1; J0_v0;
  J1: S1 => $X1; J1_k3*S1;
  J2: S1 => S2; (J2_k1*S1 - J2_k_1*S2)*(1 + J2_c*S2^J2_q);
  J3: S2 => $X2; J3_k2*S2;

  // Species initializations:
  S1 = 0;
  S2 = 1;
  X0 = 1;
  X1 = 0;
  X2 = 0;

  // Compartment initializations:
  compartment_ = 1;

  // Variable initializations:
  J0_v0 = 8;
  J1_k3 = 0;
  J2_k1 = 1;
  J2_k_1 = 0;
  J2_c = 1;
  J2_q = 3;
  J3_k2 = 5;

  // Other declarations:
  const compartment_, J0_v0, J1_k3, J2_k1, J2_k_1, J2_c, J2_q, J3_k2;
end
// -- End Antimony block

%tasks simresults.xml --master=True
// -- Begin PhraSEDML block converted from simresults.xml
// Created by libphrasedml v1.0.7
// Models
model1 = model "model1"

// Simulations
timecourse1 = simulate uniform(0, 20, 1000)

// Tasks
task0 = run timecourse1 on model1

// Repeated Tasks
task1 = repeat task0 for model1.J0_v0 in [8, 4, 0.4], reset=true

// Outputs
plot "Timecourse  (Oscli) (for v0 = 8, 4, 0.4)" task1.time vs task1.S1, task1.S2
// -- End PhraSEDML block
```

**Comment by matthiaskoenig** [comment]
I reverted the nan change for now so the notebook version works and other changes can be merged. 
I will implement a better solution for this when I find the time.

The right thing to do is to handle the DataGenerators as multi-dimensional arrays, with every repeated task an additional dimension must be added. At the end all single traces along the time are plotted.

**Pull request merged**
