### PR TITLE
Pull develop to HEAD

### PR DESCRIPTION
**Pull request by kirichoi**

### CODE REVIEW

**Comment by kirichoi** [comment]
I think the conflicts can be merged in. Any thoughts?

**Comment by kirichoi** [comment]
`develop` is now ahead of `master`. From now on, please commit to `develop` by default. PR to `master` will only occur when we draft a new release.

**Comment by hsauro** [comment]
ok got it.

I assume to get the code I switch to develop and do a clone?

Herbert

**Comment by kirichoi** [comment]
I am not sure about your setup, but if you are using git, you can simply do `git checkout develop` to change the working branch. Make sure your changes are stored properly before changing your local branch.

**Comment by hsauro** [comment]
ok I've try that. I'm not using the comand line to do git work.

Herbert

**Comment by kirichoi** [comment]
If you are editing directly through github website, you probably can go directly to the file under develop branch and edit there.

**Comment by hsauro** [comment]
That's true but I've started using git form the command line on
libstructrual so I am a bit more familar with it now.
H

**Pull request merged**
